version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - pip3 install -r requirements.txt
      - mkdocs build
      - aws s3 sync --acl public-read site/ s3://workshop.reinforce.awsdemo.me/
